import Link from "next/link";
import { PublicFooter } from "@/components/public-footer";
import { PublicHeader } from "@/components/public-header";
import { PropertyCard } from "@/components/property-card";
import { listPublicProperties, parsePublicPropertyQuery } from "@/features/properties/public-property-query";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

type PageProps = { searchParams: Promise<Record<string, string | string[] | undefined>> };
export default async function PropertiesPage({ searchParams }: PageProps) {
  const query = parsePublicPropertyQuery(await searchParams) ?? parsePublicPropertyQuery({})!;
  const [result, categories] = await Promise.all([listPublicProperties(query), prisma.category.findMany({ orderBy: { name: "asc" }, select: { name: true, slug: true } })]);
  const pageUrl = (page: number) => { const values = new URLSearchParams(); Object.entries({ ...query, page: String(page) }).forEach(([key, value]) => { if (value !== undefined) values.set(key, String(value)); }); return `/imoveis?${values}`; };
  return <><PublicHeader /><main className="page-shell"><section className="listing-heading"><p className="eyebrow">Imóveis disponíveis</p><h1>Encontre seu próximo endereço</h1><form className="filter-form" action="/imoveis"><input name="q" defaultValue={query.q} placeholder="Código, bairro, cidade ou imóvel" aria-label="Buscar imóveis" /><select name="status" defaultValue={query.status ?? ""} aria-label="Finalidade"><option value="">Venda e aluguel</option><option value="FOR_SALE">Comprar</option><option value="FOR_RENT">Alugar</option></select><select name="category" defaultValue={query.category ?? ""} aria-label="Categoria"><option value="">Todas as categorias</option>{categories.map((category) => <option key={category.slug} value={category.slug}>{category.name}</option>)}</select><input name="city" defaultValue={query.city} placeholder="Cidade" aria-label="Cidade" /><input name="neighborhood" defaultValue={query.neighborhood} placeholder="Bairro" aria-label="Bairro" /><input name="minPrice" type="number" min="1" defaultValue={query.minPrice} placeholder="Preço mínimo" aria-label="Preço mínimo" /><input name="maxPrice" type="number" min="1" defaultValue={query.maxPrice} placeholder="Preço máximo" aria-label="Preço máximo" /><select name="sort" defaultValue={query.sort} aria-label="Ordenação"><option value="newest">Mais recentes</option><option value="price_asc">Menor preço</option><option value="price_desc">Maior preço</option></select><button type="submit">Aplicar filtros</button></form></section><section aria-live="polite"><p className="result-count">{result.pagination.total} imóvel(is) encontrado(s)</p>{result.data.length ? <div className="property-grid">{result.data.map((property) => <PropertyCard key={property.id} property={property} />)}</div> : <div className="empty-state"><h2>Nenhum imóvel encontrado</h2><p>Tente ajustar sua busca ou veja todos os imóveis disponíveis.</p><Link href="/imoveis">Limpar filtros</Link></div>}{result.pagination.totalPages > 1 && <nav className="pagination" aria-label="Paginação">{query.page > 1 && <Link href={pageUrl(query.page - 1)}>Anterior</Link>}<span>Página {query.page} de {result.pagination.totalPages}</span>{query.page < result.pagination.totalPages && <Link href={pageUrl(query.page + 1)}>Próxima</Link>}</nav>}</section></main><PublicFooter /></>;
}
