import Link from "next/link";
import { redirect } from "next/navigation";
import { requireUser } from "@/auth/session";
import { prisma } from "@/lib/prisma";

type PageProps = { searchParams: Promise<Record<string, string | string[] | undefined>> };
const pageSize = 10;
const value = (input: string | string[] | undefined) => typeof input === "string" ? input.trim() : "";

export default async function AdminPropertiesPage({ searchParams }: PageProps) {
  if (!(await requireUser())) redirect("/login");
  const params = await searchParams; const q = value(params.q); const status = value(params.status); const publication = value(params.publication);
  const page = Math.max(1, Number(value(params.page)) || 1);
  const where = { deletedAt: null, ...(status ? { status: status as "FOR_SALE" | "FOR_RENT" | "SOLD" | "RENTED" } : {}), ...(publication ? { publicationState: publication as "DRAFT" | "PUBLISHED" } : {}), ...(q ? { OR: [{ title: { contains: q, mode: "insensitive" as const } }, { code: { contains: q, mode: "insensitive" as const } }, { city: { contains: q, mode: "insensitive" as const } }, { neighborhood: { contains: q, mode: "insensitive" as const } }] } : {}) };
  const [total, properties] = await prisma.$transaction([prisma.property.count({ where }), prisma.property.findMany({ where, orderBy: { updatedAt: "desc" }, skip: (page - 1) * pageSize, take: pageSize, select: { id: true, code: true, title: true, status: true, publicationState: true, city: true, state: true, category: { select: { name: true } } } })]);
  const pages = Math.max(1, Math.ceil(total / pageSize)); const href = (target: number) => "/admin/imoveis?" + new URLSearchParams({ ...(q ? { q } : {}), ...(status ? { status } : {}), ...(publication ? { publication } : {}), page: String(target) }).toString();
  return <main className="admin-shell admin-modern"><Link className="back-link" href="/admin">← Voltar ao painel</Link><header className="admin-page-heading"><div><p className="eyebrow">Administração</p><h1>Imóveis</h1><p>Gerencie, filtre e acompanhe todos os imóveis cadastrados.</p></div><Link href="/admin/imoveis/novo">＋ Novo imóvel</Link></header><form className="admin-filter-panel" action="/admin/imoveis"><input name="q" defaultValue={q} placeholder="Buscar por título, código, endereço ou cidade" aria-label="Buscar imóveis" /><select name="status" defaultValue={status} aria-label="Status"><option value="">Todos os status</option><option value="FOR_SALE">À venda</option><option value="FOR_RENT">Para aluguel</option><option value="SOLD">Vendidos</option><option value="RENTED">Alugados</option></select><select name="publication" defaultValue={publication} aria-label="Publicação"><option value="">Todos</option><option value="PUBLISHED">Publicados</option><option value="DRAFT">Rascunhos</option></select><button type="submit">Filtrar</button></form><section className="admin-table-section"><h2>{total} {total === 1 ? "imóvel encontrado" : "imóveis encontrados"}</h2>{properties.length ? <div className="admin-table"><div className="admin-table-head"><span>Imóvel</span><span>Código</span><span>Categoria</span><span>Status</span><span>Cidade</span><span>Ações</span></div>{properties.map((property) => <article key={property.id}><strong>{property.title}</strong><span>{property.code}</span><span>{property.category.name}</span><span><b className={property.publicationState === "PUBLISHED" ? "status-public" : "status-draft"}>{property.publicationState === "PUBLISHED" ? "Publicado" : "Rascunho"}</b><small>{property.status === "FOR_SALE" ? "À venda" : property.status === "FOR_RENT" ? "Aluguel" : property.status}</small></span><span>{property.city}/{property.state}</span><Link href={"/admin/imoveis/" + property.id + "/editar"}>Editar</Link></article>)}</div> : <div className="empty-state"><h2>Nenhum imóvel encontrado</h2><p>Ajuste os filtros ou cadastre um novo imóvel.</p></div>}<nav className="admin-pagination" aria-label="Paginação">{page > 1 && <Link href={href(page - 1)}>← Anterior</Link>}<span>Página {page} de {pages}</span>{page < pages && <Link href={href(page + 1)}>Próxima →</Link>}</nav></section></main>;
}
