"use client";

import { FormEvent, useEffect, useState } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";

type InitialProperty = { id: string; title: string; description: string; price: string; status: "FOR_SALE" | "FOR_RENT" | "SOLD" | "RENTED"; publicationState: "DRAFT" | "PUBLISHED"; categoryId: string; zipCode: string; street: string; number: string; complement: string | null; neighborhood: string; city: string; state: string; country: string; latitude: string | null; longitude: string | null; whatsappNumber: string; imageCount: number };
type Props = { categories: { id: string; name: string }[]; defaultWhatsappNumber: string; property?: InitialProperty };
type Preview = { file: File; url: string };
type Toast = { kind: "error" | "success"; message: string };

function formatBrl(value: string) {
  const raw = value.replace(/[R$\s]/g, "");
  if (!raw) return "";
  const normalized = raw.includes(",") ? raw.replace(/\./g, "").replace(",", ".") : raw;
  const amount = Number(normalized);
  return Number.isFinite(amount) ? new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(amount) : value;
}

export function PropertyForm({ categories, defaultWhatsappNumber, property }: Props) {
  const router = useRouter(); const editing = Boolean(property);
  const [toast, setToast] = useState<Toast | null>(null); const [loading, setLoading] = useState(false);
  const [price, setPrice] = useState(property ? formatBrl(property.price) : ""); const [previews, setPreviews] = useState<Preview[]>([]); const [coverIndex, setCoverIndex] = useState(0);
  useEffect(() => () => previews.forEach((preview) => URL.revokeObjectURL(preview.url)), [previews]);
  const showToast = (kind: Toast["kind"], message: string) => setToast({ kind, message });
  function selectFiles(event: FormEvent<HTMLInputElement>) { previews.forEach((preview) => URL.revokeObjectURL(preview.url)); setPreviews(Array.from(event.currentTarget.files ?? []).map((file) => ({ file, url: URL.createObjectURL(file) }))); setCoverIndex(0); }
  async function findCep(event: FormEvent<HTMLButtonElement>) { const form = event.currentTarget.form; const zipCode = new FormData(form!).get("zipCode")?.toString().replace(/\D/g, ""); if (!zipCode || zipCode.length !== 8) return showToast("error", "Informe um CEP com 8 dígitos."); try { const response = await fetch(`/api/admin/cep/${zipCode}`); const body = await response.json(); if (!response.ok) return showToast("error", body.error?.message ?? "Não foi possível consultar o CEP."); (["street", "neighborhood", "city", "state"] as const).forEach((field) => { const input = form?.elements.namedItem(field) as HTMLInputElement | null; if (input && body.data[field]) input.value = body.data[field]; }); showToast("success", "Endereço preenchido. Você pode ajustar os campos."); } catch { showToast("error", "Não foi possível consultar o CEP. Tente novamente."); } }
  async function uploadImages(id: string) { if (!previews.length) return; const images = new FormData(); previews.forEach(({ file }) => images.append("files", file)); images.append("primaryIndex", String(coverIndex)); const response = await fetch(`/api/admin/properties/${id}/images`, { method: "POST", body: images }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Não foi possível enviar as imagens."); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); setToast(null); const values = Object.fromEntries([...new FormData(event.currentTarget).entries()].filter(([key]) => key !== "files"));
    try {
      let id = property?.id;
      if (!editing) { values.publicationState = "DRAFT"; const response = await fetch("/api/admin/properties", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Não foi possível salvar o imóvel."); id = body.data.id; await uploadImages(id!); }
      else { if (values.publicationState === "PUBLISHED" && property!.imageCount === 0 && previews.length) await uploadImages(id!); const response = await fetch(`/api/admin/properties/${id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Não foi possível atualizar o imóvel."); if (!(values.publicationState === "PUBLISHED" && property!.imageCount === 0)) await uploadImages(id!); }
      router.push("/admin/imoveis"); router.refresh();
    } catch (error) { showToast("error", error instanceof Error ? error.message : "Não foi possível salvar o imóvel."); } finally { setLoading(false); }
  }
  return <form className={`property-form${loading ? " is-loading" : ""}`} onSubmit={submit} aria-busy={loading}>
    <section><h2>Informações principais</h2><label>Título<input name="title" defaultValue={property?.title} required disabled={loading} /></label><label>Descrição<textarea name="description" defaultValue={property?.description} required minLength={10} disabled={loading} /></label><label>Preço<input name="price" value={price} onChange={(event) => setPrice(event.target.value)} onBlur={() => setPrice(formatBrl(price))} inputMode="decimal" placeholder="R$ 0,00" required disabled={loading} /></label><label>Status<select name="status" defaultValue={property?.status ?? "FOR_SALE"} disabled={loading}><option value="FOR_SALE">À venda</option><option value="FOR_RENT">Para aluguel</option><option value="SOLD">Vendido</option><option value="RENTED">Alugado</option></select></label><label>Categoria<select name="categoryId" defaultValue={property?.categoryId} required disabled={loading}>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label>{editing && <label>Visibilidade<select name="publicationState" defaultValue={property?.publicationState} disabled={loading}><option value="DRAFT">Rascunho</option><option value="PUBLISHED">Publicado</option></select><small>Para publicar, o imóvel precisa ter uma foto de capa.</small></label>}</section>
    <section><h2>Endereço</h2><label>CEP<div className="inline-input"><input name="zipCode" defaultValue={property?.zipCode} required disabled={loading} /><button type="button" onClick={findCep} disabled={loading}>Consultar CEP</button></div></label><label>Logradouro<input name="street" defaultValue={property?.street} required disabled={loading} /></label><label>Número<input name="number" defaultValue={property?.number} required disabled={loading} /></label><label>Complemento<input name="complement" defaultValue={property?.complement ?? ""} disabled={loading} /></label><label>Bairro<input name="neighborhood" defaultValue={property?.neighborhood} required disabled={loading} /></label><label>Cidade<input name="city" defaultValue={property?.city} required disabled={loading} /></label><label>UF<input name="state" defaultValue={property?.state} maxLength={2} required disabled={loading} /></label><input name="country" type="hidden" value={property?.country ?? "Brasil"} /></section>
    <section><h2>Fotos e contato</h2>{editing && <p className="form-note">Este imóvel possui {property!.imageCount} foto(s) cadastrada(s).</p>}<label className="image-input">Adicionar fotos<input name="files" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={selectFiles} disabled={loading} /><small>Selecione uma foto abaixo para usá-la como capa entre as novas imagens.</small></label>{previews.length > 0 && <div className="image-previews" aria-label="Prévia das imagens">{previews.map((preview, index) => <button className={`image-preview${index === coverIndex ? " is-cover" : ""}`} key={preview.url} type="button" onClick={() => setCoverIndex(index)} aria-pressed={index === coverIndex} disabled={loading}><Image src={preview.url} alt={`Prévia da imagem ${index + 1}`} fill unoptimized sizes="144px" /><span>{index === coverIndex ? "Foto de capa" : "Definir como capa"}</span></button>)}</div>}<label>Latitude<input name="latitude" type="number" step="any" defaultValue={property?.latitude ?? ""} disabled={loading} /></label><label>Longitude<input name="longitude" type="number" step="any" defaultValue={property?.longitude ?? ""} disabled={loading} /></label><label>WhatsApp<input name="whatsappNumber" defaultValue={property?.whatsappNumber ?? defaultWhatsappNumber} required disabled={loading} /></label>{!editing && <input name="publicationState" type="hidden" value="DRAFT" />}</section>
    <button type="submit" disabled={loading}>{loading ? "Salvando…" : editing ? "Salvar alterações" : "Salvar rascunho"}</button>{toast && <p className={`toast toast-${toast.kind}`} role={toast.kind === "error" ? "alert" : "status"}>{toast.message}</p>}
  </form>;
}
